---
- import_tasks: install.yml
  become: true
  tags:
    - node_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - node_exporter_configure

- name: Ensure Node Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - node_exporter_run
